# Generated by Django 4.0.2 on 2022-04-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
