# Generated by Django 4.0.2 on 2022-04-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0004_alter_student_participation_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
