# Generated by Django 4.0.2 on 2022-04-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0005_remove_professor_email_remove_professor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='organization',
        ),
    ]
