# Generated by Django 4.0.2 on 2022-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0006_remove_course_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_unique_id',
        ),
        migrations.AddField(
            model_name='course',
            name='courseName',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
