# Generated by Django 4.0.2 on 2022-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0007_remove_course_courseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
