# Generated by Django 4.0.2 on 2022-05-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0008_alter_course_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='course_name',
        ),
    ]
