# Generated by Django 4.0.2 on 2022-05-06 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrma', '0009_rename_coursename_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrma.organization'),
        ),
        migrations.AddField(
            model_name='student',
            name='organizations',
            field=models.ManyToManyField(to='hrma.Organization'),
        ),
    ]
